steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fitsync-ml-api:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fitsync-ml-api:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fitsync-ml-api'
      - '--allow-unauthenticated'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fitsync-ml-api:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast2'
      - '--memory'
      - '2Gi'
      - '--service-account'
      - 'ml-team-cloud-run@fitsync-406408.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - 'fitsync-406408:us-central1:main-mysql'
      - '--port'
      - '8080'
      - '--labels'
      - 'environment=development'
      - '--env-vars-file'
      - 'env.dev.yaml'
      - '--set-secrets'
      - 'FITSYNC_PASS=fitsync-ml-api-DB_PASSWORD:latest'
images:
  - 'gcr.io/$PROJECT_ID/fitsync-ml-api:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
